webtalk_init -webtalk_dir C:/Users/146261/Documents/IPN ESCOM/Arquitectura/Practica12_CartasASM/Practica12_CartasASM.sim/sim_1/behav/xsim/xsim.dir/Arreglo_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 26 21:06:35 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "31cb07bb-c02b-4aca-9f5f-24686cd16615" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6c0e98e9ce4946359b92620c64b18860" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A6-7310 APU with AMD Radeon R4 Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1996 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5892_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4238108540 -regid "" -xml C:/Users/146261/Documents/IPN ESCOM/Arquitectura/Practica12_CartasASM/Practica12_CartasASM.sim/sim_1/behav/xsim/xsim.dir/Arreglo_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/146261/Documents/IPN ESCOM/Arquitectura/Practica12_CartasASM/Practica12_CartasASM.sim/sim_1/behav/xsim/xsim.dir/Arreglo_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/146261/Documents/IPN ESCOM/Arquitectura/Practica12_CartasASM/Practica12_CartasASM.sim/sim_1/behav/xsim/xsim.dir/Arreglo_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
