/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Arithmetic.h"
#include <stdio.h>
#include <math.h>

float *suma_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static float  result;
	result = argp->operando1 + argp->operando2;
	return &result;
}

float *resta_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static float  result;
	result = argp->operando1 - argp->operando2;
	return &result;
}

float *multiplicacion_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static float  result;
	result = argp->operando1 * argp->operando2;
	return &result;
}

float *division_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static float  result;
	result = argp->operando1 / argp->operando2;
	return &result;
}

float *exponencial_1_svc(operandos *argp, struct svc_req *rqstp)
{
	static float  result;
	result = pow(argp->operando1, argp->operando2);
	return &result;
}
//^