/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Trigonometric.h"
#include <stdio.h>
#include <math.h>

float *seno_1_svc(float *argp, struct svc_req *rqstp)
{
	static float  result;
	result = sin(*argp);
	return &result;
}

float *coseno_1_svc(float *argp, struct svc_req *rqstp)
{
	static float  result;
	result = cos(*argp);
	return &result;
}

float *tangente_1_svc(float *argp, struct svc_req *rqstp)
{
	static float  result;
	result = tan(*argp);
	return &result;
}

float *cotangente_1_svc(float *argp, struct svc_req *rqstp)
{
	static float  result;
	result = 1/tan(*argp);
	return &result;
}

float *secante_1_svc(float *argp, struct svc_req *rqstp)
{
	static float  result;
	result = 1/cos(*argp);
	return &result;
}

float *cosecante_1_svc(float *argp, struct svc_req *rqstp)
{
	static float  result;
	result = 1/sin(*argp);
	return &result;
}

float *logaritmo_1_svc(float *argp, struct svc_req *rqstp)
{
	static float  result;
	result = log(*argp);
	return &result;
}

float *raizcuadrada_1_svc(float *argp, struct svc_req *rqstp)
{
	static float  result;
	result = sqrt(*argp);
	return &result;
}