/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRIGONOMETRIC_H_RPCGEN
#define _TRIGONOMETRIC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TRIGONOMETRIC_PRG 0x20000002
#define TRIGONOMETRIC_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define seno 1
extern  float * seno_1(float *, CLIENT *);
extern  float * seno_1_svc(float *, struct svc_req *);
#define coseno 2
extern  float * coseno_1(float *, CLIENT *);
extern  float * coseno_1_svc(float *, struct svc_req *);
#define tangente 3
extern  float * tangente_1(float *, CLIENT *);
extern  float * tangente_1_svc(float *, struct svc_req *);
#define cotangente 4
extern  float * cotangente_1(float *, CLIENT *);
extern  float * cotangente_1_svc(float *, struct svc_req *);
#define secante 5
extern  float * secante_1(float *, CLIENT *);
extern  float * secante_1_svc(float *, struct svc_req *);
#define cosecante 6
extern  float * cosecante_1(float *, CLIENT *);
extern  float * cosecante_1_svc(float *, struct svc_req *);
#define logaritmo 7
extern  float * logaritmo_1(float *, CLIENT *);
extern  float * logaritmo_1_svc(float *, struct svc_req *);
#define raizCuadrada 8
extern  float * raizcuadrada_1(float *, CLIENT *);
extern  float * raizcuadrada_1_svc(float *, struct svc_req *);
extern int trigonometric_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define seno 1
extern  float * seno_1();
extern  float * seno_1_svc();
#define coseno 2
extern  float * coseno_1();
extern  float * coseno_1_svc();
#define tangente 3
extern  float * tangente_1();
extern  float * tangente_1_svc();
#define cotangente 4
extern  float * cotangente_1();
extern  float * cotangente_1_svc();
#define secante 5
extern  float * secante_1();
extern  float * secante_1_svc();
#define cosecante 6
extern  float * cosecante_1();
extern  float * cosecante_1_svc();
#define logaritmo 7
extern  float * logaritmo_1();
extern  float * logaritmo_1_svc();
#define raizCuadrada 8
extern  float * raizcuadrada_1();
extern  float * raizcuadrada_1_svc();
extern int trigonometric_prg_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRIGONOMETRIC_H_RPCGEN */
