use PRUEBA 

USE PRUEBA

CREATE TABLE PERSONA
(
ApPAT NVARCHAR(30),
ApMat NVARCHAR(30),
Nombre NVARCHAR(30)
)

-- lista todos los objetos tipo tabla d ela base de datos
SELECT * FROM SYS.OBJECTS WHERE TYPE='U'

-- INSERT  PERSONA VALUES('','','')


INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CASANDRA')
INSERT INTO PERSONA VALUES('GUTIERREZ','MENDEZ','KENDRA')
INSERT INTO PERSONA VALUES('PALOMINO','LOPEZ','FABIAN')
INSERT INTO PERSONA VALUES('URRUTIA','GOMEZ','FERNANDO')
INSERT INTO PERSONA VALUES('BENITEZ','FERNANDEZ','FERDERICO')
INSERT INTO PERSONA VALUES('SEGOVIANO','BEAUJEAN','CARLOS')
INSERT INTO PERSONA VALUES('CALDERON','HERNANDEZ','JAVIER')
INSERT INTO PERSONA VALUES('GALEANA','FERNANDEZ','JERONIMO')
INSERT INTO PERSONA VALUES('FRAN','HERNANDEZ','JAHAIRA')
INSERT INTO PERSONA VALUES('ROSAS','DE LA O','JESUS')
INSERT INTO PERSONA VALUES('LOPEZ','GONDOLA','ELIAS')
INSERT INTO PERSONA VALUES('LOPEZ','REBOLLEDO','LUCERO')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','RAMON')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CAROLINA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','ZEFERINO')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','MA ELENA')
INSERT INTO PERSONA VALUES('LOPEZ','REBOLLEDO','SILVIA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','ALICIA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','MONSERRAT')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','JOSUE')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','DAVID')
INSERT INTO PERSONA VALUES('LOPEZ','REBOLLEDO','SALVADOR')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','GERSON')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','MAURO')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','IRIS')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','JOEL')
INSERT INTO PERSONA VALUES('LOPEZ','REBOLLEDO','MARIELY')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','PATRICIA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','TANIA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CARLA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CARLOTA')
INSERT INTO PERSONA VALUES('LOPEZ','REBOLLEDO','CARMINA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CELIA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CELESTINA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CESAR')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CHEMA')
INSERT INTO PERSONA VALUES('LOPEZ','REBOLLEDO','TLATOANI')
INSERT INTO PERSONA VALUES('LOPEZ','INSASTIGA','PEDRO')
INSERT INTO PERSONA VALUES('LOPEZ','INSASTIGA','JORGE')
INSERT INTO PERSONA VALUES('LOPEZ','INSASTIGA','ROSA')
INSERT INTO PERSONA VALUES('LOPEZ','INSASTIGA','RENE')
INSERT INTO PERSONA VALUES('LOPEZ','INSASTIGA','RENESME')
INSERT INTO PERSONA VALUES('LOPEZ','INSASTIGA','RENATA')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','ROSALBA')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','SUSANA')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','SANDRA')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','SELENE')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','CYNTHIA')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','MARISELA')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','MERCEDES')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','MAGDALENA')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','MARIA')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','MONICA')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','ALEJANDRO')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','ALEX')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','ALDO')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','ALI')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','CRISTIANO')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','MESI')
INSERT INTO PERSONA VALUES('LOPEZ','FERNANDEZ','MICHEL')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','MARCIAL')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','LEYVER')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CORI')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','SELENA')
INSERT INTO PERSONA VALUES('LOPEZ','REBOLLEDO','SERENA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','SALI')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','ROMINA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','VIOLETA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','VALERIA')
INSERT INTO PERSONA VALUES('LOPEZ','REBOLLEDO','VERONICA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','VIVIANA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','ZAYRA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','ZAMIRA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CALONICO')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CASIMIRO')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','DANIEL')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','DEMIAN')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','DARIO')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','DEVORA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','DONOVAN')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CONSUELO')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','KAREN')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','CARMEN')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','KARINA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','ANA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','ANABEL')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','ANA LUISA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','ANA LAURA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','ANASTASIA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','SILVESTRA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','SIMON')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','TAMATA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','ANTONIO')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ',' TOMAS')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','MATEO')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','FABRIZIO')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','FIDEL')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','FABIOLA')
INSERT INTO PERSONA VALUES('LOPEZ','HERNANDEZ','SARAY')
INSERT INTO PERSONA VALUES('ROMERO','LOPEZ','TANIA')

INSERT INTO PERSONA SELECT * FROM PERSONA 

SELECT COUNT(*) FROM PERSONA

select * from PERSONA
--Borrar todos los planes de memoria caché 
DBCC FREEPROCCACHE WITH NO_INFOMSGS
-- Vaciar la caché de datos 
DBCC DROPCLEANBUFFERS WITH NO_INFOMSGS

SELECT  ApPat, ApMat, Nombre
 FROM PERSONA 
WHERE ApPat='LOPEZ' and ApMat='HERNANDEZ'


--Crear un índice 

CREATE CLUSTERED INDEX CL_PERSONA ON PERSONA 
(ApPat, ApMat)-- Solo Uno 
GO

CREATE NONCLUSTERED INDEX CL_NOMBRE ON PERSONA
(NOMBRE, ApPat)
GO