CREATE TABLE Bitacora_Cita_UPD 
(
ID INT IDENTITY NOT NULL, 
operacion VARCHAR(10) DEFAULT NULL, 
usuario VARCHAR(40) DEFAULT NULL,
host VARCHAR(30) DEFAULT NULL,
modificado DATETIME DEFAULT NULL,
PK VARCHAR(5) NOT NULL, 
tabla VARCHAR(40) NOT NULL,
campo VARCHAR(30) NOT NULL,
valor VARCHAR(30) NOT NULL,
valor_nuevo  VARCHAR(30),
PRIMARY KEY (ID)
)